### ISSUE TITLE
Use serde derive instead?

### ISSUE THREAD

**Issue by tiby312** [reem/rust-ordered-float#70]
If this is a good idea, I could do a pull request
https://serde.rs/no-std.html

**Comment by mbrubeck** [comment]
Hmm.  This would simplify the code, but it would also increase the number of build-dependencies and the time required to compile them.

If I were writing this code from scratch, I would use typically use `#[derive]`.  But since the manual impls are already written, and aren't much of a maintenance burden, I don't see much reason to switch to `#[derive]`.
