### ISSUE TITLE
Why not `impl<T> Borrow<T> for NonNan<T>` ?

### ISSUE THREAD

**Issue by changhe3** [reem/rust-ordered-float#98]
It seems we can satisfy the following behavior as long as we exclude NAN:

> In particular Eq, Ord and Hash must be equivalent for borrowed and owned values: x.borrow() == y.borrow() should give the same result as x == y.

**Comment by mbrubeck** [comment]
Fixed in bfabcc9dcf66ee9297796ec44a6de3f303f007fa.  However, this has limited use because:

1. It is implemented only for `NotNan<f32>` and `NotNan<f64>`.  Implementing it for a generic `T` would be incorrect because `T` could implement `Hash` in a way that is inconsistent with `NotNan::hash`.

2. This isn't useful for `HashMap::get` or `BTreeMap::get`, because `f32` and `f64` do not implement `Hash` or `Ord` themselves.

**Comment by changhe3** [comment]
I think this is useful for the extremely rare cases where you use float as keys for range queries in data structures like [btreemultimap](https://docs.rs/btreemultimap/0.1.0/btreemultimap/).

**Comment by mbrubeck** [comment]
Unfortunately, I think that fails for the same reason. `BTreeMultiMap::<K, V>::range` has the following signature:

```rust
    pub fn range<T: ?Sized, R>(&self, range: R) -> MultiRange<'_, K, V>
    where
        T: Ord,
        K: Borrow<T>,
        R: RangeBounds<T>,
```

When `K = NotNan<f32>, R = Range<f32>, T = f32`, this fails the `T: Ord` bound.
